apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.serviceName }}
  labels:
    app: {{ .Values.serviceName }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.serviceName }}
  template:
    metadata:
      labels:
        app: {{ .Values.serviceName }}
    spec:
      containers:
      - name: app
        image: {{ .Values.image }}
        env:
          - name: NEW_RELIC_LICENSE_KEY
            valueFrom:
              secretRef:
                name: {{ .Values.serviceName }}-newrelic-key
                key: licenseKey
        ports:
        - containerPort: {{ .Values.containerPort }}
