{{- if .Values.newRelicLicenseKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serviceName }}-newrelic-key
type: Opaque
stringData:
  licenseKey: {{ .Values.newRelicLicenseKey | quote }}
{{- end }}
